web_controller:
    resource: ../../src/Controller/Web/
    type: annotation
rest_controller:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
